spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 606868
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
  resources:
    static-locations: classpath:/static/
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: springboottest.changhong.practice.test.pojo.DO
  configuration:
    map-underscore-to-camel-case: true
